### ISSUE TITLE
The URL of bricks is dead

### ISSUE THREAD

**Issue by wjguo** [microstacks/stack#5]
Hi, I followed the steps in the page https://training.play-with-docker.com/mongodb-cluster/.
The domain `bricks.pipecloud.co ` cannot be resolved. Is there a new URL?

```
[node1] (local) root@192.168.0.8 ~
$ curl -sSL https://bricks.pipecloud.co | sh
curl: (6) Could not resolve host: bricks.pipecloud.co
```

Besides, `install.microstacks.com` is dead too.

```
[node1] (local) root@192.168.0.8 ~
$ curl -sSL install.microstacks.com | sh
curl: (6) Could not resolve host: install.microstacks.com
```

**Comment by athakwani** [comment]
Try below URL for now.

```
curl -sSL https://s3.amazonaws.com/bricks.pipecloud.co/index | sed 's/ROOT_URL=https:\/\/get.dupper.co/ROOT_URL=https:\/\/s3.amazonaws.com\/bricks.pipecloud.co/'  | sh
```

**Comment by wjguo** [comment]
> Try below command to install bricks for now.
> 
> ```
> curl -sSL https://s3.amazonaws.com/bricks.pipecloud.co/index | sed 's/ROOT_URL=https:\/\/get.dupper.co/ROOT_URL=https:\/\/s3.amazonaws.com\/bricks.pipecloud.co/'  | sh
> ```

It works. Thank you!
